Controllers/LicenseController.cs
using Edev.LM;
using Edev.LM.Model;
using Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi;
using Microsoft.VisualStudio.Services.Common;
using Microsoft.VisualStudio.Services.Licensing;
using Microsoft.VisualStudio.Services.OAuth;
using Newtonsoft.Json;
using ReqIFBridge.Models;
using ReqIFBridge.Utility;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Management;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using OperationResult = Edev.LM.OperationResult;
using OperationStatusTypes = Edev.LM.OperationStatusTypes;

namespace ReqIFBridge.Controllers
{
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class LicenseController : Controller
    {
        #region Constants

        const string CONST_WEB_SERVICE_URL = "https://modernrequirements.compliance.flexnetoperations.com:443/deviceservices";
        const int CONST_PRODUCT_ID = 14;
        const string CONST_PRODUCT_NAME = "ReqIF4DevOps";
        const string CONST_PRODUCT_CODE = "F50";
        const int CONST_PRODUCT_MAJOR_VERSION = 1;
        const int CONST_PRODUCT_MINOR_VERSION = 0;
        const int CONST_PRODUCT_BUILD_VERSION = 0;
        const string CONST_PRODUCT_ENCRYPTION_KEY = "ReqIF4DevOps4314571";
        const string CONST_PRODUCT_GUID = "{B7ED3A03-8F37-426D-BDD9-58B12BC98C75}";
        const string CONST_PUBLIC_KEY = "A59Jip0lt73Xig==";
        const string CONST_TRIAL_LICENSE_KEY = "EEJX1-70200-G3E8H-18S6Z-3J1VF-SDNF97WY";
        const string CONST_VISUAL_STUDIO_COM = "visualstudio.com";
        const string CONST_DEV_AZURE_DOT_COM = "dev.azure.com";
        const string CONST_EMPTY_LICENSE_KEY = "Enter license key.";
        const string CONST_LICENSE_ACTIVATED_MSG = "Your license has been successfully activated. Please wait for a few seconds.";
        const string CONST_PRODUCT_NOT_DEFINED_MSG = "There is some error occurred in registering license manager. (See logs for error)";
        const string SESSION_ACCOUNT_NAME = "AccountName";
        const string CONST_LICENSE_FEATURE_NOT_ALLOWED_MSG = "Your License code is not valid for this product.";
        const string SESSION_LICENSE_INFORMATION = "LicenseInformation";
        const string CONST_LICENSE_EMPTY_FEATURES = "Your License code does not belong to this product.";
        const string CONST_PRODUCT_NOT_ACTIVATED_MSG = "Your product is not activated.";
        const string CONST_PRODUCT_ACTIVATED_MSG = "Your Product is ACTIVATED.";
        string CONST_LICENSE_FILES_PATH = ConfigurationManager.AppSettings.Get("License.FilesPath");
        string CONST_LICENSE_TRIAL_FILE_PATH = MvcApplication.GetTrialFilePath;
        const string CONST_CLEAR_LICENSE_SUCCESS_MSG = "Your License has been cleared. Please wait for a few seconds.";
        const string CONST_CLEAR_LICENSE_FAILED_MSG = "Your request of license clear has failed.";
        const string CONST_LICENSE_VALIDATION_FAILED_MSG = "Failed to validate account license.";
        const string CONST_LICENSE_FILE_CREATION_FAILED_MSG = "Unable to create file in specified directory.";
        const string CONST_LICENSE_INVALID_RESPONSE_FILE = "The selected response file is invalid.";
        const string CONST_LICENSE_INVALID_RESPONSE_FILE_SIZE = "The selected file size should be greater than 0.";
        const string CONST_LICENSE_INVALID_RESPONSE_FILE_CODE = "[1,7DE,9,0[70000039,2,250293]]";
        const string CONST_LICENSE_NO_REQUEST_FILE_FOUND = "Unable to find 'Generate Request File' request from this machine.";
        const string CONST_LICENSE_EMPTY_ACCOUNT_MSG = "Account name is empty or null.";
        const string CONST_LICENSE_TRIAL_FILE_NOT_FOUND = "Unable to find trial file on specified path.";
        #endregion

        #region Public_Methods
        public JsonResult ValidateLicense(AdoParams model)
        {
            DebugLogger.LogStart("LicenseController", "ValidateLicense");
            JsonResult jsonResult = Json(new { isActivated = false, data = "", message = CONST_LICENSE_VALIDATION_FAILED_MSG }, JsonRequestBehavior.AllowGet); ;
            try
            {
                jsonResult = this.ValidateLicenseCore(model);
                //GetProjectProcessId(model);                
            }
            catch (Exception ex)
            {
                DebugLogger.LogError(ex);
                
            }
            DebugLogger.LogEnd("LicenseController", "ValidateLicense");
            return jsonResult;
        }

        public static Guid GetProjectProcessId(AdoParams model)
        {
            DebugLogger.LogStart("LicenseController", "GetProjectProcessId");
            Guid currentProjectProcessID = Guid.Empty;
            string keyWithPrefix = model.ProjectId + MvcApplication.CONST_PROJECT_PROCESS_ID;
            long lngTicks = DateTime.Now.Ticks;
            if (RedisHelper.KeyExist(keyWithPrefix))
            {
                try
                {
                    currentProjectProcessID = JsonConvert.DeserializeObject<Guid>(RedisHelper.LoadFromCache(keyWithPrefix));
                    lngTicks = DateTime.Now.Ticks - lngTicks;
                    DebugLogger.LogInfo(CommonUtility.TIME_TAKEN_TO_GET_PROCESS_ID_MSG+" " + new DateTime(lngTicks).Minute + "minute " + new DateTime(lngTicks).Second + "second " + new DateTime(lngTicks).Millisecond + "millisecond.");
                    DebugLogger.LogEnd("LicenseController", "GetProjectProcessId");

                    return currentProjectProcessID;
                }
                catch (Exception ex)
                {
                    DebugLogger.LogError(ex);
                }
            }
            DebugLogger.LogInfo("ServerUri:" + model.ServerUri);
            try
            {
                VssCredentials vssCredentials =
    new VssCredentials(new VssOAuthAccessTokenCredential(model.AccessToken));
                WorkItemTrackingProcessHttpClient workItemTrackingProcessHttpClient =
                new WorkItemTrackingProcessHttpClient(new Uri(model.ServerUri), vssCredentials);

                Guid projectGuid = new Guid(model.ProjectId);
                var processList = workItemTrackingProcessHttpClient.GetListOfProcessesAsync(Microsoft.TeamFoundation.WorkItemTracking.Process.WebApi.Models.GetProcessExpandLevel.Projects).Result;
                if (processList != null)
                {
                    foreach (var process in processList)
                    {
                        if (process.Projects != null && process.Projects.Count() > 0)
                        {
                            var guid = process.Projects.FirstOrDefault(x => x.Id == projectGuid);
                            if (guid != null)
                            {
                                currentProjectProcessID = process.TypeId;
                                RedisHelper.SaveInCache(keyWithPrefix, JsonConvert.SerializeObject(currentProjectProcessID), null);

                                break;
                            }
                        }
                        else
                        {
                            DebugLogger.LogError(process.TypeId +": "+CommonUtility.UNABLE_TO_GET_PROJECT_LIST_MSG);
                            
                        }                      
                    }
                }

                lngTicks = DateTime.Now.Ticks - lngTicks;
                DebugLogger.LogInfo(CommonUtility.TIME_TAKEN_TO_GET_PROCESS_ID_MSG + " " + new DateTime(lngTicks).Minute + "minute " + new DateTime(lngTicks).Second + "second " + new DateTime(lngTicks).Millisecond + "millisecond.");
            }
            catch (Exception ex)
            {
                DebugLogger.LogError(ex);
                            
            }

            DebugLogger.LogEnd("LicenseController", "GetProjectProcessId");
            return currentProjectProcessID;
        }
        public JsonResult ActivateProductLicense(LicenseType licenseType, string licKey, string licenseServerURL)
        {
            DebugLogger.LogStart("LicenseController", "ActivateProductLicense");
            JsonResult jsonResult = Json(new { });
            try
            {
                if (string.IsNullOrEmpty(licKey) || licenseType == LicenseType.None)
                {
                    jsonResult = Json(new { validated = false, reason = CONST_EMPTY_LICENSE_KEY, statuscode = "" });
                    DebugLogger.LogError(CONST_EMPTY_LICENSE_KEY);
                    DebugLogger.LogEnd("LicenseController", "ActivateProductLicense");
                    return jsonResult;
                }
                string accountName = this.AccountName.ToLower();
                LicenseInfo licenseInfo = this.ActivateProductLicenseCore(accountName, licenseType, licKey, licenseServerURL);

                if (licenseInfo == null || !licenseInfo.ProductDefined)
                {
                    jsonResult = Json(new { validated = false, reason = CONST_PRODUCT_NOT_DEFINED_MSG, statuscode = "" });

                }
                else
                {
                    if (!licenseInfo.LicenseValidated)
                    {
                        jsonResult = Json(new { validated = false, reason = licenseInfo.LicenseActivationFailedMessage, statuscode = "" });
                    }
                    else if (licenseInfo.AllowedFeatures == null || !licenseInfo.AllowedFeatures.Contains(CONST_PRODUCT_CODE))
                    {
                        jsonResult = Json(new { validated = false, reason = CONST_LICENSE_FEATURE_NOT_ALLOWED_MSG, statuscode = "" });
                    }
                    else
                    {
                        LicenseInformation = licenseInfo;
                        jsonResult = Json(new { validated = true, reason = CONST_LICENSE_ACTIVATED_MSG, statuscode = "" });
                    }
                }
            }

Views/Default/ConfirmationModal.cshtml
@{
    string parentContainer = ViewBag.ControlId;
    string confirmDialogWindow = "confirm-dialog-window-" + ViewBag.ControlId;
    string confirmDialogTitleText = "confirm-dialog-titletext-" + ViewBag.ControlId;
    string confirmDialogMsgText = "confirm-dialog-textmsg-" + ViewBag.ControlId;
    string dialogOkButtonName = "confirm-dialog-ok-button-" + ViewBag.ControlId;
    string dialogCancelButtonName = "confirm-dialog-cancel-button-" + ViewBag.ControlId;
    string dialogNoButtonName = "confirm-dialog-no-button-" + ViewBag.ControlId;
}
<div id="@parentContainer">

    <!-- Modal -->
    <div class="modal fade" id=@confirmDialogWindow data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id=@confirmDialogTitleText></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p  id=@confirmDialogMsgText></p>
                </div>
                <div class="modal-footer" >
                    <div style="font-size:small;">
                        <button type="button" class="btn btn-info" data-dismiss="modal" id=@dialogOkButtonName onclick="onConfirmationDialogOkButtonClick(this)" data-parentcontainerid=@parentContainer>Ok</button>
                        <button type="button" class="btn btn-light" data-dismiss="modal" id=@dialogCancelButtonName onclick="onConfirmationDialogCancelButtonClick(this)" data-parentcontainerid=@parentContainer>Cancel</button>
                        <button type="button" class="btn btn-light" data-dismiss="modal" id=@dialogNoButtonName onclick="onConfirmationDialogNoButtonClick(this)" data-parentcontainerid=@parentContainer>No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Default/ExportReqIFAction.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExportReqIF</title>
    @*<script src="~/Scripts/jQuery/jquery-3.4.1.min.js"></script>*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/vsssdk")
    <script src="~/Scripts/JSUtility.js"></script>
    <script>
        VSS.init({
            usePlatformScripts: true,
            usePlatformStyles: true
        });

        function isEmptyGuid(str) {
            return str === "00000000-0000-0000-0000-000000000000";
        }

        // Use an IIFE to create an object that satisfies the IContributedMenuSource contract
        var menuContributionHandler = (function() {

            "use strict";
            return {
                // This is a callback that gets invoked when a user clicks the newly contributed button item
                // The actionContext parameter contains context data surrounding the circumstances of this
                // action getting invoked.
                execute: function(actionContext) {


                    if (actionContext.workItemIds && actionContext.workItemIds.length <= 0) {
                        JSUtility.showVstsMessageDialog("Error", "This operation cannot be performed because no work item exist.");
                        return;
                    }

                    if (actionContext.query) {
                        if (!actionContext.query.path && actionContext.query.name && actionContext.query.name === "Recycle Bin") {
                            JSUtility.showVstsMessageDialog("Error", "This operation cannot be performed on deleted work items.");
                            return;
                        }
                    }


                    VSS.getService(VSS.ServiceIds.Dialog).then(function(dialogService) {
                        var extensionCtx = VSS.getExtensionContext();
                        // Build absolute contribution ID for dialogContent
                        var contributionId = extensionCtx.publisherId + "." + extensionCtx.extensionId + ".dialog-ReqIFBridge-ReqIF-Export";

                        // Show dialog
                        var dialogOptions = {
                            title: "ReqIF Export",
                            width: 1200,
                            height: 570,
                            resizable: false,
                            buttons: null
                            //okText: "Export",
                            //getDialogResult: function() {
                            //    return;
                            //},
                            //okCallback: function (result) {
                            //    // Log the result to the console
                            //    console.log('Export Clicked');
                            //}
                        };
                        var workItemIds = [];
                       /* console.log(actionContext.workItemIds);*/
                        if (actionContext) {
                            if (actionContext.ids) {
                                workItemIds.push(actionContext.workItemIds);
                            } else if (actionContext.team) {
                                workItemIds.push(actionContext.workItemIds);
                            }
                            else if (actionContext.queryText) {
                                workItemIds = [];
                                var wiql = actionContext.query.id;

                                if (isEmptyGuid(wiql)) {
                                    wiql = actionContext.query.wiql;
                                }
                            } else {
                                workItemIds = [];
                            }
                        } else {
                            JSUtility.showVstsMessageDialog("Error", "This operation cannot be performed because no work item exist.");
                            return;
                        }

                        sessionStorage.setItem('reqIFBridge-ReqIFExport-WorkItemIDs', workItemIds);
                        sessionStorage.setItem('reqIFBridge-ReqIFExport-Wiql', wiql);
                        sessionStorage.setItem("reqIFBridge-ReqIFExport-Action-Dialog-Close", "false");
                        @*sessionStorage.setItem("ig-vsts-compareWorkItem-compareWiSubHubId", "@ViewBag.CompareWiSubHubId");
                            sessionStorage.setItem('ig-vsts-compareWorkItem-extensionPointIdentification', "@ViewBag.ExtensionPointIdentification");
                            sessionStorage.setItem("ig-vsts-compareWorkItem-loginDialogId", "@ViewBag.loginDialogContributerId");*@

                        dialogService.openDialog(contributionId, dialogOptions).then(function(dialog) {
                            //dialog.updateOkButton(true);

                            var intervalId = setInterval(function() {
                                var closeDialog = sessionStorage.getItem("reqIFBridge-ReqIFExport-Action-Dialog-Close");
                                var sendRequest = sessionStorage.getItem("reqIFBridge-ReqIFExport-Action-Dialog-InProgress");
                                if (sendRequest === "true") {
                                    if ($.isFunction(dialog.showBusyOverlay)) {
                                        dialog.showBusyOverlay();
                                    }
                                } else {
                                    if ($.isFunction(dialog.hideBusyOverlay)) {
                                        dialog.hideBusyOverlay();
                                    }
                                }

                                if (closeDialog === "true") {
                                    dialog.close();
                                    sessionStorage.removeItem("reqIFBridge-ReqIFExport-Action-Dialog-Close");
                                    sessionStorage.removeItem("reqIFBridge-ReqIFExport-Action-Dialog-InProgress");
                                    clearInterval(intervalId);
                                }

                            }, 200);

                        });
                    });
                }
            };
        }());

        // Associate the menuContributionHandler object with the "btnSmartReport" button contribution from the manifest.
        VSS.register("button-ReqIFBridge-ReqIF-Export", menuContributionHandler);
    </script>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/Default/ExportReqIFDialog.cshtml
@using Kendo.Mvc.UI
@using ReqIFBridge.Models

@{
    Layout = null;
    string adoParamModel = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ExportReqIFDialog</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/vsssdk")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Kendo/KendoScripts")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Kendo/kendo.metro")
    @Styles.Render("~/Content/Kendo/kendo.common")
    @Styles.Render("~/Content/Kendo/kendo.rtl")
    @Styles.Render("~/Content/Kendo/kendo.dataviz.metro")

    <script src="~/Scripts/jQuery/jquery.fileDownload.min.js"></script>

    <script>var serverUrl = '@Request.Url.Scheme://@Request.Url.Authority';</script>

    <script src="~/Scripts/License/license.js"></script>
    <script src="~/Scripts/ConfirmationModalPlugins.js"></script>
    <script src="~/Scripts/ExportConfirmationPlugin.js"></script>

    <script src="~/Scripts/Default/ExportReqIFDialog.js" ></script>
    <link rel="stylesheet" href="~/Content/License/license-style.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/reqIF-style.css" type="text/css" />


</head>

<body>

    <div class="container" style="margin-left: 0; margin-right: 0; max-width: none; display: none;" id="main-div">

        @{
            Html.RenderAction("LicenseActivationDialog", "License", new { callingViewId = "ExportReqIFDialog" });
        }

        <div id="reqIFBridge-ReqIFExport-MainDiv">


            <div class="row">
                <div class="col-sm-12">
                    <span>Work item(s) selected for export.</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div id="Grid" class="reqif-export-grid" style="height: 350px; width: 100%;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div id="lic-trial-notification" style="display:none;">
                        <span style="color:#FF0000;">
                            <i style="font-size: smaller;">
                                Only 30 records per transaction are allowed in trial version
                            </i>
                        </span>

                    </div>
                </div>
            </div>

            <div class="row" style="margin-top:10px;">

                <div class="col-sm-6">
                    <button id="exportReqIF" class="btn btn-info" onclick="javascript: validateMappingFile();">Export</button>

                    <button id="removeCacheReqIF" title="This will clear the cache of current project" class="btn btn-light" onclick="javascript: onClearCache();">Clear Cache</button>


                    @*<button id="closeReqIF" class="btn btn-light" onclick="javascript: onCloseDialog();">Cancel</button>*@
                </div>
                <div class="col-sm-6 text-right">
                    <a href="#" id="expmappinglink" onclick="onViewMappingConfirmationOk();" oncontextmenu="return false;">
                        Configure Mapping
                    </a>
                </div>


            </div>
            <div class="row" style="margin-top:5px;">
                <div class="col-sm-12">
                    <div id="result" style="line-height: 38px;">
                    </div>
                </div>


            </div>

        </div>

        <div id="export-confirmation-dialog"></div>
        <div id="export-option-confirmation-dialog"></div>
    </div>

    <div class="modal fade" id="detailsModal" tabindex="-1" role="dialog" aria-labelledby="detailsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="detailsModalLabel">Work Item Discrepancy Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <textarea id="detailsModalContent" class="form-control" rows="15" readonly style="white-space: pre-wrap;"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Views/Default/ImportReqIFDialog.cshtml
@using System.Web.Mvc.Html
@using Kendo.Mvc.UI
@using System.Configuration

@{
    Layout = null;
    string adoParamModel = null;
    HttpPostedFileBase fileobject;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ImportReqIFDialog</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/vsssdk")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Kendo/KendoScripts")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Kendo/kendo.metro")
    @Styles.Render("~/Content/Kendo/kendo.common")
    @Styles.Render("~/Content/Kendo/kendo.rtl")
    @Styles.Render("~/Content/Kendo/kendo.dataviz.metro")

    <script src="~/Scripts/jQuery/jquery.fileDownload.min.js"></script>

    <script>
        var serverUrl = '@Request.Url.Scheme://@Request.Url.Authority';

        @{
            bool filePath = false;
            if (ViewBag.FilePath != null )
            {
                filePath = ViewBag.FilePath;
            }
        }
        var reqIfImportFilePath = @Json.Encode(filePath);


    </script>

    <script src="~/Scripts/License/license.js"></script>
    <script src="~/Scripts/ConfirmationModalPlugins.js"></script>
    <script src="~/Scripts/Default/ImportReqIFDialog.js"></script>

    <link rel="stylesheet" href="~/Content/License/license-style.css" type="text/css" />
    <link rel="stylesheet" href="~/Content/reqIF-style.css" type="text/css" />

    <style>
        .k-upload-button {
            background-color: rgb(0, 120, 212);
            color: white;
        }
    </style>

</head>
<body>


    <div class="container" style="margin-left: 0; margin-right: 0; max-width: none; display:none;" id="main-div">

        @{
            Html.RenderAction("LicenseActivationDialog", "License", new { callingViewId = "ImportReqIFDialog" });
        }

        <div id="reqIFBridge-ReqIFImport-MainDiv">
            <div class="row" style="margin-top:2px;">

                <div class="col-sm-5">
                    <form enctype="multipart/form-data">
                        <div class="row">
                            <div class="col-sm-12">
                                <div id="lic-trial-notification" style="display:none;">
                                    <span style="color:#FF0000;">
                                        <i style="font-size: smaller;">
                                            *Only 30 records per transaction are allowed in trial version
                                        </i>
                                    </span>

                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <span>
                                    Please follow below steps:
                                </span>
                            </div>
                        </div>

                        <div class="row" style="margin-top:5px;">
                            <div class="col-sm-12">
                                <span>

                                    1. Select and upload the ReqIF specification file, exported from any RM tool supporting ReqIF standard.
                                </span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">
                                <span><br />All supported ReqIF extensions: (*.reqif,*.reqifz) </span>
                            </div>



                        </div>

                        <div class="row" style="margin-top:10px;">
                            <div class="col-sm-12">
                                <div>
                                    @*Product Backlog Item 32450: Start*@
                                    <input name="reqIFFile" id="reqIFFile" type="file" title="Select a required ReqIF file to upload" accept=".reqif,.reqifz,.reqifw" />
                                    @*Product Backlog Item 32450: End*@
                                </div>

                            </div>
                        </div>

                        <div class="row" style="margin-top:10px;">
                            <div style="margin-top:10px; margin-left:15px">
                                <span style="color: #008000;">
                                    <i style="font-size: smaller;" id="indicateFileSelection">
                                    </i>
                                    <a href="#" onclick="javascript: ReloadMainPage()" oncontextmenu="return false;">
                                        <i style="font-size: smaller;" id="reloadPageLink">
                                        </i>
                                    </a>
                                    <i style="font-size: smaller;" id="clearSelection">
                                    </i>
                                </span>
                            </div>
                            <div class="col-sm-12" style="margin-top:10px;">
                                <span>2. To configure mapping for ReqIF Import or to view the existing mapping on server, click Configure Mapping link.  </span>
                            </div>
                        </div>

                        <div class="row" style="margin-top:5px;">
                            <div class="col-sm-12">

                                <a href="#" id="expmappinglink" onclick="javascript: ValidateReqIFFile('Connecting to Azure DevOps Services...')"  oncontextmenu="return false;">
                                    Configure Mapping
                                </a>
                            </div>
                        </div>


                    </form>
                </div>

                <div class="col-sm-7">
                    <img class="img-fluid" src="~/Content/images/ReqIF_Blue.png" alt="ReqIF4Devops">
                </div>

            </div>
            <div class="row" style="margin-top:5px;">
                <div class="col-sm-12">
                    <input id="importReqIF" class="btn btn-info" value="Import" style="float: left; max-width:100px;" onclick="javascript: validateMappingFile();" />

                    <input id="importClearCacheReqIF" title="This will clear the cache of current project" class="btn btn-light" value="Clear Cache" style="float: left; max-width: 135px; margin-left: 5px;" onclick="javascript: onClearCache();" />
                </div>
             
                 <br />  
                <div class="col-sm-12" style="margin-top:5px;">
                    <p id="result" style="line-height: 38px;">
                    </p>
                </div>
                
        </div>

        </div>
        <div id="import-confirmation-dialog" data-myval="false"></div>
    </div>
</body>
</html>

Views/Default/Index.cshtml
@{
    // ViewBag.Title = "ReqIF Bridge";
    var _buildVersion = ViewBag.BuildVersion;
}

<h2>ReqIF4DevOps service is running....(Build Version: @_buildVersion)</h2>
<br />
<h3><b>About ReqIF4DevOps</b></h3>
<p>ReqIF4DevOps allows users to exchange their requirements and data with any tool that supports the ReqIF Standard. It enables the user to define mapping based on their needs while importing the requirements. </p>
<br />
<p>ADO users can now import/export requirements with a single click, thanks to ReqIF4DevOps. Not just that, anybody with a requirement authoring tool that supports the ReqIF Standard can export their requirements to Microsoft ADO, and, similarly, an ADO user can export their requirements to any other tool that supports the ReqIF Standard. </p>
<br />
<p>ReqIF4DevOps provides organized requirements data in the form of individual requirements that may be viewed in terms of attributes, structure, related elements, etc. </p>
<br />
<img src="~/Content/images/ReqIF_Blue.png" />